---
name: Bot-BasicBot-Pluggable-Module-VieDeMerde
version: 0.1
author:
  - 'Olivier Schwander <iderrick@cpan.org>'
abstract: VieDeMerde plugin for BasicBot::Pluggable
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Bot::BasicBot::Pluggable::Module::VieDeMerde:
    file: lib/Bot/BasicBot/Pluggable/Module/VieDeMerde.pm
    version: 0.1
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
